version: '3.8'

services:
  mysql:
    image: mysql
    container_name: tora-mysql-container
    # environment:
    # MYSQL_ROOT_PASSWORD: test
    # MYSQL_DATABASE: tora_db
    env_file:
      - .env
    ports:
      - '3306:3306'

  # nestjs_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-food-app
  #   depends_on:
  #     - mysql
  #   ports:
  #     - '5000:5000'
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   environment:
  #     - PORT=${PORT}
